//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaylistSyncGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TargetMusicFolder {
            get {
                return ((string)(this["TargetMusicFolder"]));
            }
            set {
                this["TargetMusicFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TargetPlaylistFilePath {
            get {
                return ((string)(this["TargetPlaylistFilePath"]));
            }
            set {
                this["TargetPlaylistFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourcePlalyistFilePath {
            get {
                return ((string)(this["SourcePlalyistFilePath"]));
            }
            set {
                this["SourcePlalyistFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConversionsAsJson {
            get {
                return ((string)(this["ConversionsAsJson"]));
            }
            set {
                this["ConversionsAsJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MusicLibraryPlaylists {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MusicLibraryPlaylists"]));
            }
            set {
                this["MusicLibraryPlaylists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MusicLibraryFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MusicLibraryFolders"]));
            }
            set {
                this["MusicLibraryFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Portable Programs\\kid3-3.7.0-win32\\kid3.exe")]
        public string kid3_FilePath {
            get {
                return ((string)(this["kid3_FilePath"]));
            }
            set {
                this["kid3_FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Notepad++\\notepad++.exe")]
        public string notepadPlusPlus_FilePath {
            get {
                return ((string)(this["notepadPlusPlus_FilePath"]));
            }
            set {
                this["notepadPlusPlus_FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>jpg</string>
  <string>png</string>
  <string>m3u</string>
  <string>wpl</string>
  <string>pls</string>
  <string>ini</string>
  <string>ffs_db</string>
  <string>db</string>
  <string>pdf</string>
  <string>reapeaks</string>
  <string>stignore</string>
  <string>txt</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection nonAudioDataTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["nonAudioDataTypes"]));
            }
            set {
                this["nonAudioDataTypes"] = value;
            }
        }
    }
}
